✨ :: Header 컴포넌트 1차
team-boheom/boheom-frontend pull request #8
Opened 2024-01-21 12:58 UTC by Ulement92

반응형은 어떻게 하는건가요..?

2024-01-21 13:12 UTC, KANGYONGSU23 commented on src/components/Header_.jsx
> +        <LogOut>로그아웃</LogOut>
클릭했을 때 페이지 이동하게 해주세요

2024-01-21 13:12 UTC, KANGYONGSU23 commented on src/components/Header_.jsx
> +const Write = styled.text`
text는 무슨 태그에요?

2024-01-21 13:12 UTC, KANGYONGSU23 commented on src/components/Header_.jsx
> +const Write = styled.text`
첨봤는데?

2024-01-21 13:12 UTC, KANGYONGSU23 commented on src/components/Header_.jsx
> +`;
이름만 다르고 스타일은 다 똑같으니까 이름 하나로 통일 합시다

2024-01-21 13:12 UTC, KANGYONGSU23 commented on src/components/Header_.jsx
> +  cursor: pointer;
폰트 스타일도 맞춰 주세요

2024-01-21 13:12 UTC, KANGYONGSU23 commented on src/pages/Main.jsx
> +      <Header />
헤더를 이렇게 넣으면 모든 페이지 마다 하나씩 넣어야 하잖아요? 그러면 중복된 코드가 생기고...
그래서 MainRouter.js에 한 번만 넣으면 모든 페이지에 적용됩니다.

2024-01-21 13:21 UTC, Juone2 requested changes

2024-01-21 13:21 UTC, Juone2 commented on src/components/Header_.jsx
> +`;
text라는 태그도 잇음???????????????

2024-01-21 13:25 UTC, KANGYONGSU23 commented on src/components/Header_.jsx
> +};
전체적으로 디자인 좀 더 맞춰주세요. 피그마보고.
양쪽 여백이라던가 폰트 스타일, 간격, 이미지 크기 같은?

2024-01-21 13:31 UTC, KANGYONGSU23 commented on src/components/Header_.jsx
> +const Header = () => {
파일 이름에 언더바는 무슨 의미인가요?
Header_.jsx ?

2024-01-21 13:43 UTC, KANGYONGSU23 commented on src/components/Header_.jsx
> +`;
position: fixed 해주세요.
스크롤 해도 화면에 고정되게

2024-01-21 14:31 UTC, Ulement92 commented on src/components/Header_.jsx
> +const Header = () => {
이거 언더바 안넣었을 때 오류가 생기길래.. 일단 임시로 넣어놨어용..

2024-01-21 14:33 UTC, KANGYONGSU23 commented on src/components/Header_.jsx
> +const Header = () => {
무슨 오류요?

2024-01-22 07:15 UTC, Ulement92 commented on src/components/Header_.jsx
> +const Header = () => {
오 안나요!!

2024-01-22 07:21 UTC, Ulement92 commented on src/components/Header_.jsx
> +const Header = () => {
![image](https://github.com/team-boheom/boheom-frontend/assets/103026978/9432bab5-0327-4851-a827-4495f3027cb8)

2024-01-22 07:47 UTC, KANGYONGSU23 approved these changes
로고 눌렀을 때 메인페이지로 이동하게만 해주세요 👍
그리고 헤더 배경색도 넣어주시고

2024-01-23 00:41 UTC, Juone2 approved these changes

2024-01-23 10:29 UTC, merged